import { Link } from 'react-router-dom'
import { useApp } from '../AppContext'

const features = [{ number: '01', title: 'Meet your people', text: 'Find classmates, study partners and collaborators who are moving in the same direction.' }, { number: '02', title: 'Share what matters', text: 'Bring your questions, ideas and useful resources into a space built for learning.' }, { number: '03', title: 'Make progress visible', text: 'Build an academic profile that captures your interests, work and next big idea.' }]

export default function Home() {
  const { state } = useApp()
  return <main className="page home-page"><section className="hero-section"><div className="hero-copy"><div className="eyebrow">The Richfield student network</div><h1>Find your people.<br /><em>Build what’s next.</em></h1><p className="hero-lede">A focused academic community for Richfield students to connect, exchange ideas and turn curiosity into momentum.</p><div className="hero-actions"><Link to={state.isAuthenticated ? '/feed' : '/signup'} className="button primary">{state.isAuthenticated ? 'Open community' : 'Create your profile'} <span>↗</span></Link><Link to="/about" className="text-link">Explore the platform <span>→</span></Link></div></div><div className="hero-art"><div className="orbit orbit-one"></div><div className="orbit orbit-two"></div><div className="hero-note note-top"><span>R</span><div><strong>Richfield Connect</strong><small>Built around your campus</small></div></div><div className="hero-card card-main"><span className="card-label">TODAY’S DISCUSSION</span><h3>What are you<br />learning this week?</h3><div className="card-footer"><div className="avatar-stack"><span>AM</span><span>TK</span><span>LN</span></div><small>+ 128 students joined</small></div></div><div className="hero-note note-bottom"><span>↗</span><div><strong>Ideas travel further</strong><small>when shared together</small></div></div></div></section><section className="feature-section"><div className="section-heading"><div><div className="eyebrow">One community, many directions</div><h2>Make campus feel<br /><em>a little closer.</em></h2></div><p>Richfield Connect keeps academic life human. A simple place to ask, contribute and find the next useful conversation.</p></div><div className="feature-grid">{features.map((feature) => <div className="feature-item" key={feature.number}><span className="feature-number">{feature.number}</span><h3>{feature.title}</h3><p>{feature.text}</p><Link to={state.isAuthenticated ? '/feed' : '/signup'}>Learn more <span>↗</span></Link></div>)}</div></section><section className="quote-band"><p>“The best work happens in the space between<br /><em>‘I have a question’</em> and <em>‘let’s figure it out.’”</em></p><span>— Richfield Connect community principle</span></section></main>
}
